# Generated by Django 4.0.4 on 2022-05-02 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Family',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('description', models.TextField(null=True)),
                ('slug', models.SlugField(max_length=250)),
                ('category', models.CharField(choices=[('sankastaharaganapati', 'sankasta hara'), ('satyanarayana', 'satyanarayana'), ('regulars', 'regular')], default='draft', max_length=60)),
            ],
            options={
                'ordering': ('-title',),
            },
        ),
    ]
